name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore Dot/Dot.sln
    - name: Build Solution
      run: dotnet build Dot/Dot.sln --no-restore
    - name: Run Automated Tests
      run: dotnet test Dot.Tests/Dot.Tests.csproj --no-build --verbosity normal
